# dataset constants
PROJECT_PATH              = "../"  # TODO change when migrating this notebook
DATA_PATH                 = PROJECT_PATH + "data/"
FIGURES_PATH              = PROJECT_PATH + "figures/"
DANMINI_DOORBELL_DIR      = DATA_PATH + "Danmini_Doorbell/"
ENNIO_DOORBELL_DIR        = DATA_PATH + "Ennio_Doorbell/"
ECOBEE_THERMOSTAT_DIR     = DATA_PATH + "Ecobee_Thermostat/"
PHILIPS_BABY_MONITOR_DIR  = DATA_PATH + "Philips_B120N10_Baby_Monitor/"
PROV_737_SECURITY_CAM_DIR = DATA_PATH + "Provision_PT_737E_Security_Camera/"
PROV_838_SECURITY_CAM_DIR = DATA_PATH + "Provision_PT_838_Security_Camera/"
SAMSUNG_WEB_CAM_DIR       = DATA_PATH + "Samsung_SNH_1011_N_Webcam/"
SH_1002_SECURITY_CAM_DIR  = DATA_PATH + "SimpleHome_XCS7_1002_WHT_Security_Camera/"
SH_1003_SECURITY_CAM_DIR  = DATA_PATH + "SimpleHome_XCS7_1003_WHT_Security_Camera/"

BENIGN_TRAFFIC_FILE  = "benign_traffic.csv"
GAFGYT_ATTACKS_DIR   = "gafgyt_attacks/"
GAFGYT_COMBO_FILE    = GAFGYT_ATTACKS_DIR + "combo.zip"
GAFGYT_JUNK_FILE     = GAFGYT_ATTACKS_DIR + "junk.zip"
GAFGYT_SCAN_FILE     = GAFGYT_ATTACKS_DIR + "scan.zip"
GAFGYT_TCP_FILE      = GAFGYT_ATTACKS_DIR + "tcp.zip"
GAFGYT_UDP_FILE      = GAFGYT_ATTACKS_DIR + "udp.zip"
MIRAI_ATTACKS_DIR    = "mirai_attacks/"
MIRAI_ACK_FILE       = MIRAI_ATTACKS_DIR + "ack.zip"
MIRAI_SCAN_FILE      = MIRAI_ATTACKS_DIR + "scan.zip"
MIRAI_SYN_FILE       = MIRAI_ATTACKS_DIR + "syn.zip"
MIRAI_UDP_FILE       = MIRAI_ATTACKS_DIR + "udp.zip"
MIRAI_UDPPLAIN_FILE  = MIRAI_ATTACKS_DIR + "udpplain.zip"

# df cols
src_mac_ip_L5_weight             = 'src_mac_ip_L5_weight'
src_mac_ip_L5_mean               = 'src_mac_ip_L5_mean'
src_mac_ip_L5_variance           = 'src_mac_ip_L5_variance'
src_mac_ip_L3_weight             = 'src_mac_ip_L3_weight'
src_mac_ip_L3_mean               = 'src_mac_ip_L3_mean'
src_mac_ip_L3_variance           = 'src_mac_ip_L3_variance'
src_mac_ip_L1_weight             = 'src_mac_ip_L1_weight'
src_mac_ip_L1_mean               = 'src_mac_ip_L1_mean'
src_mac_ip_L1_variance           = 'src_mac_ip_L1_variance'
src_mac_ip_L0_1_weight           = 'src_mac_ip_L0.1_weight'
src_mac_ip_L0_1_mean             = 'src_mac_ip_L0.1_mean'
src_mac_ip_L0_1_variance         = 'src_mac_ip_L0.1_variance'
src_mac_ip_L0_01_weight          = 'src_mac_ip_L0.01_weight'
src_mac_ip_L0_01_mean            = 'src_mac_ip_L0.01_mean'
src_mac_ip_L0_01_variance        = 'src_mac_ip_L0.01_variance'
src_ip_L5_weight                 = 'src_ip_L5_weight'
src_ip_L5_mean                   = 'src_ip_L5_mean'
src_ip_L5_variance               = 'src_ip_L5_variance'
src_ip_L3_weight                 = 'src_ip_L3_weight'
src_ip_L3_mean                   = 'src_ip_L3_mean'
src_ip_L3_variance               = 'src_ip_L3_variance'
src_ip_L1_weight                 = 'src_ip_L1_weight'
src_ip_L1_mean                   = 'src_ip_L1_mean'
src_ip_L1_variance               = 'src_ip_L1_variance'
src_ip_L0_1_weight               = 'src_ip_L0.1_weight'
src_ip_L0_1_mean                 = 'src_ip_L0.1_mean'
src_ip_L0_1_variance             = 'src_ip_L0.1_variance'
src_ip_L0_01_weight              = 'src_ip_L0.01_weight'
src_ip_L0_01_mean                = 'src_ip_L0.01_mean'
src_ip_L0_01_variance            = 'src_ip_L0.01_variance'
src_dst_ip_L5_weight             = 'src_dst_ip_L5_weight'
src_dst_ip_L5_mean               = 'src_dst_ip_L5_mean'
src_dst_ip_L5_std                = 'src_dst_ip_L5_std'
src_dst_ip_L5_magnitude          = 'src_dst_ip_L5_magnitude'
src_dst_ip_L5_radius             = 'src_dst_ip_L5_radius'
src_dst_ip_L5_covariance         = 'src_dst_ip_L5_covariance'
src_dst_ip_L5_pcc                = 'src_dst_ip_L5_pcc'
src_dst_ip_L3_weight             = 'src_dst_ip_L3_weight'
src_dst_ip_L3_mean               = 'src_dst_ip_L3_mean'
src_dst_ip_L3_std                = 'src_dst_ip_L3_std'
src_dst_ip_L3_magnitude          = 'src_dst_ip_L3_magnitude'
src_dst_ip_L3_radius             = 'src_dst_ip_L3_radius'
src_dst_ip_L3_covariance         = 'src_dst_ip_L3_covariance'
src_dst_ip_L3_pcc                = 'src_dst_ip_L3_pcc'
src_dst_ip_L1_weight             = 'src_dst_ip_L1_weight'
src_dst_ip_L1_mean               = 'src_dst_ip_L1_mean'
src_dst_ip_L1_std                = 'src_dst_ip_L1_std'
src_dst_ip_L1_magnitude          = 'src_dst_ip_L1_magnitude'
src_dst_ip_L1_radius             = 'src_dst_ip_L1_radius'
src_dst_ip_L1_covariance         = 'src_dst_ip_L1_covariance'
src_dst_ip_L1_pcc                = 'src_dst_ip_L1_pcc'
src_dst_ip_L0_1_weight           = 'src_dst_ip_L0.1_weight'
src_dst_ip_L0_1_mean             = 'src_dst_ip_L0.1_mean'
src_dst_ip_L0_1_std              = 'src_dst_ip_L0.1_std'
src_dst_ip_L0_1_magnitude        = 'src_dst_ip_L0.1_magnitude'
src_dst_ip_L0_1_radius           = 'src_dst_ip_L0.1_radius'
src_dst_ip_L0_1_covariance       = 'src_dst_ip_L0.1_covariance'
src_dst_ip_L0_1_pcc              = 'src_dst_ip_L0.1_pcc'
src_dst_ip_L0_01_weight          = 'src_dst_ip_L0.01_weight'
src_dst_ip_L0_01_mean            = 'src_dst_ip_L0.01_mean'
src_dst_ip_L0_01_std             = 'src_dst_ip_L0.01_std'
src_dst_ip_L0_01_magnitude       = 'src_dst_ip_L0.01_magnitude'
src_dst_ip_L0_01_radius          = 'src_dst_ip_L0.01_radius'
src_dst_ip_L0_01_covariance      = 'src_dst_ip_L0.01_covariance'
src_dst_ip_L0_01_pcc             = 'src_dst_ip_L0.01_pcc'
src_dst_ip_jit_L5_weight         = 'src_dst_ip_jit_L5_weight'
src_dst_ip_jit_L5_mean           = 'src_dst_ip_jit_L5_mean'
src_dst_ip_jit_L5_variance       = 'src_dst_ip_jit_L5_variance'
src_dst_ip_jit_L3_weight         = 'src_dst_ip_jit_L3_weight'
src_dst_ip_jit_L3_mean           = 'src_dst_ip_jit_L3_mean'
src_dst_ip_jit_L3_variance       = 'src_dst_ip_jit_L3_variance'
src_dst_ip_jit_L1_weight         = 'src_dst_ip_jit_L1_weight'
src_dst_ip_jit_L1_mean           = 'src_dst_ip_jit_L1_mean'
src_dst_ip_jit_L1_variance       = 'src_dst_ip_jit_L1_variance'
src_dst_ip_jit_L0_1_weight       = 'src_dst_ip_jit_L0.1_weight'
src_dst_ip_jit_L0_1_mean         = 'src_dst_ip_jit_L0.1_mean'
src_dst_ip_jit_L0_1_variance     = 'src_dst_ip_jit_L0.1_variance'
src_dst_ip_jit_L0_01_weight      = 'src_dst_ip_jit_L0.01_weight'
src_dst_ip_jit_L0_01_mean        = 'src_dst_ip_jit_L0.01_mean'
src_dst_ip_jit_L0_01_variance    = 'src_dst_ip_jit_L0.01_variance'
src_dst_ip_port_L5_weight        = 'src_dst_ip_port_L5_weight'
src_dst_ip_port_L5_mean          = 'src_dst_ip_port_L5_mean'
src_dst_ip_port_L5_std           = 'src_dst_ip_port_L5_std'
src_dst_ip_port_L5_magnitude     = 'src_dst_ip_port_L5_magnitude'
src_dst_ip_port_L5_radius        = 'src_dst_ip_port_L5_radius'
src_dst_ip_port_L5_covariance    = 'src_dst_ip_port_L5_covariance'
src_dst_ip_port_L5_pcc           = 'src_dst_ip_port_L5_pcc'
src_dst_ip_port_L3_weight        = 'src_dst_ip_port_L3_weight'
src_dst_ip_port_L3_mean          = 'src_dst_ip_port_L3_mean'
src_dst_ip_port_L3_std           = 'src_dst_ip_port_L3_std'
src_dst_ip_port_L3_magnitude     = 'src_dst_ip_port_L3_magnitude'
src_dst_ip_port_L3_radius        = 'src_dst_ip_port_L3_radius'
src_dst_ip_port_L3_covariance    = 'src_dst_ip_port_L3_covariance'
src_dst_ip_port_L3_pcc           = 'src_dst_ip_port_L3_pcc'
src_dst_ip_port_L1_weight        = 'src_dst_ip_port_L1_weight'
src_dst_ip_port_L1_mean          = 'src_dst_ip_port_L1_mean'
src_dst_ip_port_L1_std           = 'src_dst_ip_port_L1_std'
src_dst_ip_port_L1_magnitude     = 'src_dst_ip_port_L1_magnitude'
src_dst_ip_port_L1_radius        = 'src_dst_ip_port_L1_radius'
src_dst_ip_port_L1_covariance    = 'src_dst_ip_port_L1_covariance'
src_dst_ip_port_L1_pcc           = 'src_dst_ip_port_L1_pcc'
src_dst_ip_port_L0_1_weight      = 'src_dst_ip_port_L0.1_weight'
src_dst_ip_port_L0_1_mean        = 'src_dst_ip_port_L0.1_mean'
src_dst_ip_port_L0_1_std         = 'src_dst_ip_port_L0.1_std'
src_dst_ip_port_L0_1_magnitude   = 'src_dst_ip_port_L0.1_magnitude'
src_dst_ip_port_L0_1_radius      = 'src_dst_ip_port_L0.1_radius'
src_dst_ip_port_L0_1_covariance  = 'src_dst_ip_port_L0.1_covariance'
src_dst_ip_port_L0_1_pcc         = 'src_dst_ip_port_L0.1_pcc'
src_dst_ip_port_L0_01_weight     = 'src_dst_ip_port_L0.01_weight'
src_dst_ip_port_L0_01_mean       = 'src_dst_ip_port_L0.01_mean'
src_dst_ip_port_L0_01_std        = 'src_dst_ip_port_L0.01_std'
src_dst_ip_port_L0_01_magnitude  = 'src_dst_ip_port_L0.01_magnitude'
src_dst_ip_port_L0_01_radius     = 'src_dst_ip_port_L0.01_radius'
src_dst_ip_port_L0_01_covariance = 'src_dst_ip_port_L0.01_covariance'
src_dst_ip_port_L0_01_pcc        = 'src_dst_ip_port_L0.01_pcc'

# dataset dictionary keys
BENIGN_TRAIN     = "benign_train"
BENIGN_TEST      = "benign_test"
GAFGYT_COMBO     = "gafgyt_combo"
GAFGYT_JUNK      = "gafgyt_junk"
GAFGYT_SCAN      = "gafgyt_scan"
GAFGYT_TCP       = "gafgyt_tcp"
GAFGYT_UDP       = "gafgyt_udp"
MIRAI_ACK        = "mirai_ack"
MIRAI_SCAN       = "mirai_scan"
MIRAI_SYN        = "mirai_syn"
MIRAI_UDP        = "mirai_udp"
MIRAI_UDPPLAIN   = "mirai_udpplain"